insert into regiones (id,nombre) values (1,'Sudamérica');
insert into regiones (id,nombre) values (2,'Centromérica');
insert into regiones (id,nombre) values (3,'Norteamérica');
insert into regiones (id,nombre) values (4,'Europa');
insert into regiones (id,nombre) values (5,'Asia');
insert into regiones (id,nombre) values (6,'Africa');
insert into regiones (id,nombre) values (7,'Oceanía');
insert into regiones (id,nombre) values (8,'Antártida');

insert into clientes (region_id, nombre, apellido, email, create_at) values (1,'Jonas', 'Courtenay', 'jcourtenay0@com.com', '2019-11-14');
insert into clientes (region_id, nombre, apellido, email, create_at) values (1,'Kass', 'Klausewitz', 'kklausewitz1@hp.com', '2020-03-01');
insert into clientes (region_id, nombre, apellido, email, create_at) values (1,'Wyndham', 'Barbey', 'wbarbey2@biblegateway.com', '2020-05-22');
insert into clientes (region_id, nombre, apellido, email, create_at) values (1,'Emlen', 'Bisco', 'ebisco3@weebly.com', '2019-10-01');
insert into clientes (region_id, nombre, apellido, email, create_at) values (1,'Lambert', 'Fyldes', 'lfyldes4@naver.com', '2019-07-05');
insert into clientes (region_id, nombre, apellido, email, create_at) values (1,'Paco', 'Cromley', 'pcromley5@un.org', '2020-03-20');
insert into clientes (region_id, nombre, apellido, email, create_at) values (1,'Jilleen', 'Gyves', 'jgyves6@vkontakte.ru', '2019-11-28');
insert into clientes (region_id, nombre, apellido, email, create_at) values (1,'Kayla', 'Kynder', 'kkynder7@reverbnation.com', '2019-09-29');
insert into clientes (region_id, nombre, apellido, email, create_at) values (1,'Vern', 'Chastagnier', 'vchastagnier8@ebay.com', '2019-09-01');
insert into clientes (region_id, nombre, apellido, email, create_at) values (2,'Arnold', 'Orry', 'aorry9@typepad.com', '2019-11-09');
insert into clientes (region_id, nombre, apellido, email, create_at) values (2,'Marissa', 'Janicek', 'mjaniceka@netvibes.com', '2019-10-13');
insert into clientes (region_id, nombre, apellido, email, create_at) values (2,'Eugen', 'Darlison', 'edarlisonb@fotki.com', '2019-09-06');
insert into clientes (region_id, nombre, apellido, email, create_at) values (2,'Jermain', 'Chander', 'jchanderc@sogou.com', '2019-07-23');
insert into clientes (region_id, nombre, apellido, email, create_at) values (2,'Gabie', 'Tolhurst', 'gtolhurstd@ucsd.edu', '2019-12-10');
insert into clientes (region_id, nombre, apellido, email, create_at) values (2,'Leela', 'Osbourne', 'losbournee@marketwatch.com', '2019-10-18');
insert into clientes (region_id, nombre, apellido, email, create_at) values (2,'Junina', 'Abbyss', 'jabbyssf@tuttocitta.it', '2019-06-28');
insert into clientes (region_id, nombre, apellido, email, create_at) values (2,'Morey', 'Elderton', 'meldertong@yale.edu', '2019-07-07');
insert into clientes (region_id, nombre, apellido, email, create_at) values (3,'Kimmie', 'Levine', 'klevineh@twitpic.com', '2020-05-08');
insert into clientes (region_id, nombre, apellido, email, create_at) values (3,'Sydney', 'Leworthy', 'sleworthyi@vistaprint.com', '2020-05-15');
insert into clientes (region_id, nombre, apellido, email, create_at) values (3,'Aldridge', 'Rymell', 'arymellj@bluehost.com', '2020-02-05');
insert into clientes (region_id, nombre, apellido, email, create_at) values (3,'Cary', 'Jachimiak', 'cjachimiakk@psu.edu', '2019-09-23');
insert into clientes (region_id, nombre, apellido, email, create_at) values (3,'Eleanora', 'Fildery', 'efilderyl@free.fr', '2019-12-07');
insert into clientes (region_id, nombre, apellido, email, create_at) values (3,'Shari', 'Wink', 'swinkm@berkeley.edu', '2019-10-19');
insert into clientes (region_id, nombre, apellido, email, create_at) values (3,'Bambie', 'Phorsby', 'bphorsbyn@ustream.tv', '2020-04-01');
insert into clientes (region_id, nombre, apellido, email, create_at) values (3,'Fredelia', 'Nairn', 'fnairno@springer.com', '2019-08-08');
insert into clientes (region_id, nombre, apellido, email, create_at) values (3,'Ase', 'Forker', 'aforkerp@dyndns.org', '2019-07-02');
insert into clientes (region_id, nombre, apellido, email, create_at) values (3,'Brigid', 'While', 'bwhileq@usatoday.com', '2019-09-03');
insert into clientes (region_id, nombre, apellido, email, create_at) values (4,'Jobi', 'Blow', 'jblowr@amazon.de', '2020-05-04');
insert into clientes (region_id, nombre, apellido, email, create_at) values (4,'Ricardo', 'Pennycook', 'rpennycooks@amazon.co.jp', '2019-12-17');
insert into clientes (region_id, nombre, apellido, email, create_at) values (4,'Jeri', 'Collacombe', 'jcollacombet@disqus.com', '2019-09-26');
insert into clientes (region_id, nombre, apellido, email, create_at) values (4,'Gena', 'Sondland', 'gsondlandu@cnbc.com', '2020-01-28');
insert into clientes (region_id, nombre, apellido, email, create_at) values (4,'Jsandye', 'Esome', 'jesomev@github.com', '2019-12-10');
insert into clientes (region_id, nombre, apellido, email, create_at) values (4,'Deni', 'Chimes', 'dchimesw@clickbank.net', '2020-04-12');
insert into clientes (region_id, nombre, apellido, email, create_at) values (4,'Tuck', 'Petrecz', 'tpetreczx@symantec.com', '2020-04-06');
insert into clientes (region_id, nombre, apellido, email, create_at) values (4,'Ulberto', 'Talboy', 'utalboyy@statcounter.com', '2019-08-20');
insert into clientes (region_id, nombre, apellido, email, create_at) values (4,'Daren', 'Markie', 'dmarkiez@youku.com', '2020-01-05');
insert into clientes (region_id, nombre, apellido, email, create_at) values (4,'Everett', 'Treacher', 'etreacher10@whitehouse.gov', '2019-07-10');
insert into clientes (region_id, nombre, apellido, email, create_at) values (4,'Chariot', 'Dinnage', 'cdinnage11@g.co', '2020-04-16');
insert into clientes (region_id, nombre, apellido, email, create_at) values (4,'Clayton', 'Thirst', 'cthirst12@cnn.com', '2020-04-08');
insert into clientes (region_id, nombre, apellido, email, create_at) values (5,'Vyky', 'Chesney', 'vchesney13@slideshare.net', '2020-03-07');
insert into clientes (region_id, nombre, apellido, email, create_at) values (5,'Lynde', 'Van der Kruijs', 'lvanderkruijs14@live.com', '2019-09-03');
insert into clientes (region_id, nombre, apellido, email, create_at) values (5,'Wilma', 'Coughtrey', 'wcoughtrey15@dyndns.org', '2019-09-27');
insert into clientes (region_id, nombre, apellido, email, create_at) values (5,'Arabele', 'Witherdon', 'awitherdon16@ask.com', '2020-03-18');
insert into clientes (region_id, nombre, apellido, email, create_at) values (6,'Doralin', 'Le Barr', 'dlebarr17@hatena.ne.jp', '2020-03-24');
insert into clientes (region_id, nombre, apellido, email, create_at) values (6,'Juliana', 'Tatem', 'jtatem18@oaic.gov.au', '2019-10-24');
insert into clientes (region_id, nombre, apellido, email, create_at) values (6,'Sammy', 'Lauret', 'slauret19@slashdot.org', '2019-09-28');
insert into clientes (region_id, nombre, apellido, email, create_at) values (7,'Johannah', 'Shemelt', 'jshemelt1a@ask.com', '2019-09-01');
insert into clientes (region_id, nombre, apellido, email, create_at) values (7,'Kit', 'Luno', 'kluno1b@ifeng.com', '2019-08-10');
insert into clientes (region_id, nombre, apellido, email, create_at) values (8,'Valeria', 'Waddup', 'vwaddup1c@eepurl.com', '2019-06-14');
insert into clientes (region_id, nombre, apellido, email, create_at) values (8,'Camey', 'McGowan', 'cmcgowan1d@webnode.com', '2020-05-08');